name: Deploy Hexo Blog

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write # 允许写入仓库内容，这是 peaceiris/actions-gh-pages 所需的
      pages: write    # 允许写入 GitHub Pages
      id-token: write

    steps:
      - name: Checkout Source Branch
        uses: actions/checkout@v4

      - name: Setup Node.js Environment # 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm' # 启用 npm 缓存，自动缓存 node_modules 以加速后续构建

      - name: Install Dependencies
        run: npm ci # 使用 npm ci (clean install) 安装。

      - name: Generate Hexo Static Files # 生成 Hexo 静态文件
        run: npx hexo generate

      - name: Deploy to GitHub Pages # 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Hexo 默认的静态文件输出目录
          publish_branch: gh-pages # 将生成的静态文件部署到 'main' 分支
          user_name: 'github-actions[bot]' # 自定义部署提交的作者名称
          user_email: 'github-actions[bot]@users.noreply.github.com' # 自定义部署提交的作者邮箱
          commit_message: 'Deploy Hexo Blog from source branch [skip ci]' # 自定义部署提交信息。
                                                                          # [skip ci] 标签可以防止在部署分支上意外触发其他 CI/CD 工作流。
          # 清空分支会导致 CNAME 配置文件丢失。
          force_orphan: false     # 保留提交历史
          keep_files: false       # 删除旧文件